### ISSUE TITLE
通过Siri关闭空调时会被设置为制冷模式。

### ISSUE THREAD

**Issue by hiouttime** [Taosky/homebridge-lirc-aircon#1]
因看到您资料是在中国，擅自使用中文，如有不便非常抱歉。
通过Siri关闭空调时，Siri会把空调调整为制冷模式。
想请问一下您有没有遇到过这种问题。以及如何解决，非常感谢！

**Comment by Taosky** [comment]
确实存在这个问题，排查了一下，还是找不到问题所在，甚至把制冷模式删了都不行，目前好像解决不了，实在抱歉。

解决方案的话可以和Siri说“空调自动”，代码已经写死自动为关闭；也可以通过设定场景，自定义Siri指令，不过和家庭设备有关系的比如包含"空调"字眼的应该都不行。还是推荐第一种方法。

**Comment by hiouttime** [comment]
好的，明白了。非常感谢您的帮助。
和您一样，在此之前也试着排查这个问题，但是实在是不清楚为什么Siri单独操控的时候总是偏向于设置制冷模式。
感谢您提供的解决方案，的确能解决这个问题。
非常感谢。

**Comment by hiouttime** [comment]
暂时没有问题了，您可以关掉这个issues了
